version: '3.8'
services:
    dev-db:
        image: postgres:15
        ports:
            - 5434:5432
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        networks:
            - mynetwork
networks:
    mynetwork:
